const weatherDescriptions = {
  0: "Ciel dégagé",
  1: "Principalement clair",
  2: "Partiellement nuageux",
  3: "Nuageux",
  45: "Brouillard",
  48: "Brouillard givrant",
  51: "Bruine légère",
  53: "Bruine modérée",
  55: "Bruine dense",
  56: "Bruine verglaçante légère",
  57: "Bruine verglaçante dense",
  61: "Pluie légère",
  63: "Pluie modérée",
  65: "Pluie dense",
  66: "Pluie verglaçante légère",
  67: "Pluie verglaçante dense",
  71: "Neige légère",
  73: "Neige modérée",
  75: "Neige dense",
  77: "Grains de neige",
  80: "Averses légères",
  81: "Averses modérées",
  82: "Averses violentes",
  85: "Averses de neige légères",
  86: "Averses de neige violentes",
};

export const getWeatherDescription = (code) => weatherDescriptions[code] || "Description non disponible";
